# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import connections_pb2 as connections__pb2


class ConnectionsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.find_contacts = channel.unary_unary(
                '/Connections/find_contacts',
                request_serializer=connections__pb2.ConnectionRequest.SerializeToString,
                response_deserializer=connections__pb2.ConnectionResponse.FromString,
                )


class ConnectionsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def find_contacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectionsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'find_contacts': grpc.unary_unary_rpc_method_handler(
                    servicer.find_contacts,
                    request_deserializer=connections__pb2.ConnectionRequest.FromString,
                    response_serializer=connections__pb2.ConnectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Connections', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Connections(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def find_contacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Connections/find_contacts',
            connections__pb2.ConnectionRequest.SerializeToString,
            connections__pb2.ConnectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
