apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
    nodePort: 30092
  - name: "9093"
    port: 9093
    targetPort: 9092
    nodePort: 30093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 9092
          env:
          - name: KAFKA_BROKER_ID
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: KAFKA_BROKER_ID          
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: KAFKA_INTER_BROKER_LISTENER_NAME
          - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          - name: KAFKA_CFG_LISTENERS
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: KAFKA_CFG_LISTENERS
          - name: KAFKA_CFG_ADVERTISED_LISTENERS
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: KAFKA_CFG_ADVERTISED_LISTENERS
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: KAFKA_INTER_BROKER_LISTENER_NAME
          - name: KAFKA_CFG_ZOOKEEPER_CONNECT
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: KAFKA_CFG_ZOOKEEPER_CONNECT
          - name: ALLOW_PLAINTEXT_LISTENER
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: ALLOW_PLAINTEXT_LISTENER

