apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-apiconnection
  name: udaconnect-apiconnection
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30003
  selector:
    service: udaconnect-apiconnection
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-apiconnection
  name: udaconnect-apiconnection
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-apiconnection
  template:
    metadata:
      labels:
        service: udaconnect-apiconnection
    spec:
      containers:
      - image: punjwaniakbar/udaconnect-apiconnection:latest
        name: udaconnect-apiconnection
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: KAFKA_SERVER
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_SERVER
        - name: KAFKA_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_PORT
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_TOPIC
        - name: API_PERSON_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: API_PERSON_HOST
        - name: API_PERSON_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: API_PERSON_PORT
        - name: API_LOCATION_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: API_LOCATION_HOST
        - name: API_LOCATION_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: API_LOCATION_PORT
        - name: API_CONNECTION_GRPCHOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: API_CONNECTION_GRPCHOST
        - name: API_CONNECTION_GRPCPORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: API_CONNECTION_GRPCPORT

      restartPolicy: Always
