apiVersion: v1
kind: Service
metadata:
  name: udaconnect-grpcconnections
  labels:
    app: udaconnect-grpcconnections
spec:
  type: NodePort
  selector:
    app: udaconnect-grpcconnections
  ports:
  - name: "50051"
    port: 50051
    targetPort: 50051
    nodePort: 30051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-grpcconnections
  name: udaconnect-grpcconnections
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-grpcconnections
  template:
    metadata:
      labels:
        service: udaconnect-grpcconnections
    spec:
      containers:
      - image: punjwaniakbar/udaconnect-grpcconnections:latest
        name: udaconnect-grpcconnections
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: KAFKA_SERVER
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_SERVER
        - name: KAFKA_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_PORT
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_TOPIC
      restartPolicy: Always
