apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-grpcconnections
  name: udaconnect-grpcconnections
spec:
  ports:
  - name: "50051"
    port: 50051
    targetPort: 50051
    nodePort: 30151
  selector:
    service: udaconnect-grpcconnections
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-grpcconnections
  name: udaconnect-grpcconnections
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-grpcconnections
  template:
    metadata:
      labels:
        service: udaconnect-grpcconnections
    spec:
      containers:
      - image: punjwaniakbar/udaconnect-grpcconnections:latest
        name: udaconnect-grpcconnections
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "256m"
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: KAFKA_SERVER
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_SERVER
        - name: KAFKA_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_PORT
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_TOPIC
        - name: API_PERSON_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: API_PERSON_HOST
        - name: API_PERSON_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: API_PERSON_PORT
        - name: API_LOCATION_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: API_LOCATION_HOST
        - name: API_LOCATION_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: API_LOCATION_PORT
        - name: API_CONNECTION_GRPCHOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: API_CONNECTION_GRPCHOST
        - name: API_CONNECTION_GRPCPORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: API_CONNECTION_GRPCPORT
      restartPolicy: Always
