apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  type: NodePort
  selector:
    app: zookeeper
  ports:
  - name: "2181"
    port: 2181
    targetPort: 2181
    nodePort: 32181
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 2181
          env:
          - name: ALLOW_ANONYMOUS_LOGIN
            valueFrom:
              configMapKeyRef:
                name: db-env
                key: ALLOW_ANONYMOUS_LOGIN
